### ISSUE TITLE
AdamRMS Dark Mode

### ISSUE THREAD

**Issue by cherry-john** [bstudios/adam-rms#95]
**Is your feature request related to a problem? Please describe.**
It's a bit bright when using AdamRMS in the dark or at night

**Describe the solution you'd like**
A dark mode for the RMS.

**Describe alternatives you've considered**
Burning my retinas every time I use the rms in the dark.

**Comment by chriscn** [comment]
This is absolutely required.

**Comment by Robert-Watts** [comment]
I was thinking about this one last night, because bootstrap is used, we could theoretically just pull out the colour variables, edit the colours to the theme we want, and recompile bootstrap as dark. Then in the head.php file we can just call a different CSS file. 

It does however mean this solution is server side not client side. But this would be a quicker fix than a full client side solution.
 
All of that said, it doesn't really add to the usability of the RMS. I dunno 🤷‍♂️ Exams make brain go mush

**Comment by cherry-john** [comment]
I would argue that some sort of server-side implementation for dark mode is a good thing, as it allows consistency across devices. No idea what the 'proper' way to do this is though

**Comment by Robert-Watts** [comment]
@Jbithell Can I just ask, is there a practical reason you had not upgraded adminLTE from version 3.0.* to 3.1.*?

If there is no reason particularly it may be relatively easy as the new version of adminLTE adds native support for dark mode. I have tested this on a couple pages as shown below:

![image](https://user-images.githubusercontent.com/11817698/119569460-abd4c180-bda6-11eb-83f8-b9d21ed81e62.png)


![image](https://user-images.githubusercontent.com/11817698/119569281-6dd79d80-bda6-11eb-824e-07b653e0578d.png)

**Comment by Jbithell** [comment]
@Robert-Watts sorry didn't upgrade as simply didn't get the chance (came out in late March I think).

Do the honours and bump us to 3.1, feat Dark Mode!

I agree with @cherry-john, this should sit in the DB (potentially users table) for persistence.
